project:
  type: website
  output-dir: docs

website:
  title: "Laura M. Bandi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: edu.qmd
        text: Education
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: paser.qmd
        text: PASER Lab

format:
  html:
    includes:
      in_header: <script src="https://kit.fontawesome.com/2a27c9068a.js" crossorigin="anonymous"></script>
    theme: darkly
    css: styles.css
    toc: false
    page-layout: full
