project:
  type: website
  output-dir: docs

website:
  title: "Laura M. Bandi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - edu.qmd
      - research.qmd
      - teaching.qmd 
      - paser.qmd

format:
  html:
    theme:
      light: pulse 
      dark: cyborg
    css: styles.css
    toc: false
    page-layout: full