---
title: "Research"
---

## Presentations

**Bandi, L.**, & Counsell, A. (2025, July 31). *The S-BLIS: A short-form measure to improve statistical literacy assessment.* \[Paper Presentation\]. Researchers of Statistics Education (RoSE) eConference 2025.

**Bandi, L.**, & Counsell, A. (2025, June 12-14). Statistical literacy: A necessary skill with limited measures. In A. Counsell (Chair), *Assessing and teaching critical thinking in research methods and statistics: How are we doing?* \[Symposium\]. 86^th^ Annual Canadian Psychological Association Convention, St. John’s, NL, Canada.

**Bandi, L.**, Halili-Sychangco, D., Crone, G., & Counsell, A. (2024, June 21-23). The state of undergraduate statistics courses: Are we teaching modern skills in psychology? In R. Cribbie (Chair), *Rethinking the Teaching of Statistics for Student Betterment* \[Symposium\]. 85th Annual Canadian Psychological Association Convention, Ottawa, ON, Canada.

**Bandi, L.** (2024, March 26). *Exploring statistical literacy: Measures, psychological factors, and pedagogical approaches* \[Area talk\]. Toronto Metropolitan University Social Area Meeting (SAM), Toronto, ON, Canada.

## Posters

\*Kala, B., \*Gongati, S., **Bandi, L.**, & Rao, V. N. V. (2025, July 17-19). *Can using AI tools to do statistics broaden participation in STEM?* \[Poster Presentation\]. Consortium for the Advancement of Undergraduate Statistics Education (CAUSE) Research Satellite, Ames, Iowa, USA

**Bandi, L.**, Loock, J., & Counsell, A. (2024, December 11-12). *Hand calculations vs. software? Student attitudes about their value mirror their instructors* \[Poster Presentation\]. PsychTERMS 2024 Virtual Conference.

Loock, J., **Bandi, L.**, & Counsell, A. (2024, December 11-12). *Are we overstating the ubiquity of statistics anxiety in psychology? Meta-analytic evidence and insights* \[Poster Presentation\]. PsychTERMS 2024 Virtual Conference.

Counsell, A., **Bandi, L.**, Loock, J., Herbert, M., & Martin, J. (2023, December 13-14). *Using jamovi to support equitable access and learning in undergraduate statistics courses* \[Poster Presentation\]. PsychTERMS 2023 Virtual Conference.

\*denotes student mentee

## Research Experience

### Student Research Analyst

Government of Canada\
*Sept. 2025 – Present*

### Research Assistant

University of Illinois Urbana-Champaign\
*Jan. 2025 – Present*\
**PI:** Dr. V. N. Vimal Rao

**PASER Lab** – Toronto Metropolitan University\
*June 2022 – Present*\
**PI:** Dr. Alyssa Counsell

### Research Practicum Student

**Mathematical Thinking Lab** – Ontario Institute for Studies in Education of the University of Toronto\
*May 2023 – July 2024*\
**PI:** Dr. Zachary Hawes
